name: wgd
channels:
  - conda-forge
  - bioconda
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.8
  - wgd
  - fasttree
  - pip
  - pip:
      - attrs==20.3.0
      - biopython==1.76
      - click==7.1.2
      - colorama==0.4.4
      - commonmark==0.9.1
      - cycler==0.10.0
      - ete3==3.1.3
      - fastcluster==1.1.28
      - humanfriendly==8.2
      - importlib-metadata==3.1.0
      - iniconfig==1.1.1
      - jinja2==2.11.2
      - joblib==0.11
      - kdepy==1.1.0
      - kiwisolver==1.2.0
      - markupsafe==1.1.1
      - matplotlib==3.2.2
      - numexpr==2.8.6
      - numpy==1.19.0
      - packaging==20.4
      - pandas==1.4.4
      - pillow==8.4.0
      - pluggy==0.13.1
      - plumbum==1.6.9
      - progressbar2==3.51.4
      - psutil==5.7.0
      - py==1.9.0
      - pygments==2.7.2
      - pyparsing==2.4.7
      - pyqt5==5.12.3
      - pyqt5-sip==12.15.0
      - pyqtwebengine==5.12.1
      - pytest==6.1.2
      - python-dateutil==2.9.0.post0
      - python-utils==2.4.0
      - pytz==2020.1
      - pyyaml==5.3.1
      - rich==12.5.1
      - scikit-learn==0.23.1
      - scikit-learn-extra==0.2.0
      - scipy==1.5.4
      - seaborn==0.10.1
      - six==1.15.0
      - threadpoolctl==2.1.0
      - toml==0.10.2
      - tornado==6.0.4
      - tqdm==4.67.1
      - typing-extensions==4.13.0
      - zipp==3.4.0
