name: Lint (Python)

on:
  push:
  pull_request:
      types: [ opened, reopened, synchronize ]

jobs:
  website:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.13' ]

    name: Website (${{ matrix.python-version }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            .github
            website
          sparse-checkout-cone-mode: false

      - name: "Make Subdirectory Root."
        run: |
          ls -lAh
          mv website/* .
          rm -rf website
          ls -lAh

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: '0.6.9'
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Project and Dependencies
        run: uv sync --all-extras --dev

      - name: Run Linter
        uses: astral-sh/ruff-action@v3
        with:
          args: check

      - name: Run Formatter
        uses: astral-sh/ruff-action@v3
        with:
          args: format --check --diff

      - name: Run pyright
        uses: jakebailey/pyright-action@v2
        with:
          version: '1.1.397'
          warnings: false

  wgd_manager:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.13' ]

    name: WGD Manager (${{ matrix.python-version }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            .github
            tools/wgd_manager
          sparse-checkout-cone-mode: false

      - name: "Make Subdirectory Root."
        run: |
          ls -lAh
          mv tools/wgd_manager/* .
          rm -rf tools
          ls -lAh

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: '0.6.9'
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Project and Dependencies
        run: uv sync --all-extras --dev

      - name: Run Linter
        uses: astral-sh/ruff-action@v3
        with:
          args: check

      - name: Run Formatter
        uses: astral-sh/ruff-action@v3
        with:
          args: format --check --diff

      - name: Run pyright
        uses: jakebailey/pyright-action@v2
        with:
          version: '1.1.397'
          warnings: false
