name: Lint (SCSS)

on:
  workflow_dispatch:
  push:
    paths:
      - 'bit/static/scss/**'
  pull_request:
      types: [ opened, reopened, synchronize ]
      paths:
        - 'bit/static/scss/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './bit/static'
    strategy:
      fail-fast: false

    name: Style Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            bit/static
          sparse-checkout-cone-mode: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'bit/static/package-lock.lock'

      - name: Install Packages
        run: npm ci

      - name: Run stylelint
        run: |
          npx stylelint "./scss/**/*.scss" --config .stylelintrc
