name: Lint (SCSS)

on:
  workflow_dispatch:
  push:
    paths:
      - 'website/bit/static/scss/**'
  pull_request:
      types: [ opened, reopened, synchronize ]
      paths:
        - 'website/bit/static/scss/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false    

    name: Style Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            website/.stylelintrc
            website/bit/static

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Packages
        run: |
          npm i stylelint-config-standard-scss

      - name: Run stylelint
        uses: actions-hub/stylelint@master
        env:
          PATTERN: "./website/**/*.scss"
          CONFIG_PATH: "website/.stylelintrc"
