name: Setup uv (Monorepo)

on:
  workflow_call:
    inputs:
      version:
        description: 'The version of uv to install.'
        required: false
        type: string
      python-version:
        description: 'The version of python to install.'
        required: false
        type: string
      directory:
        description: 'Which directory the project is in and make root.'
        required: true
        type: string

jobs:
  setup_uv_monorepo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            ${{ inputs.directory }}
          sparse-checkout-cone-mode: false

      - name: "Make Subdirectory Root."
        run: |
          ls -lAh
          mv ${{ inputs.directory }}/* .
          rm -rf ${{ inputs.directory }}
          ls -lAh

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ inputs.version }}
          python-version: ${{ inputs.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Project and Dependencies
        run: uv sync --all-extras --dev
  